#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-CoreMIDI
version:      0.05
version_from: lib/Mac/CoreMIDI.pm
installdirs:  site
requires:
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
